### ISSUE TITLE
Add Recurrence Option

### ISSUE THREAD

**Issue by XopherDesign** [CreativeAcer/SPFxCountdownTimer#3]
Add a property for recurrence, something like
Recurrence - Repeat Every Week [ X ]
                   - Repeat Every 2 Weeks
                   - Repeat Every Month
Hour(s) Before Resetting: [ 1 ]

This way if you set the date for Friday October 4th at 5pm and Repeat every week, and 1 hour before resetting, when Friday October 4th at 5pm the timer would read all 0's but then at 6pm it would switch over to countdown to Friday October 11th at 5pm.

This way you could do things like payday calendars and other repeating events.

Thanks,
Chris

**Comment by CreativeAcer** [comment]
Thats a good idea, i will look into this
