### ISSUE TITLE
Configuration is not being preserved

### ISSUE THREAD

**Issue by XopherDesign** [CreativeAcer/SPFxCountdownTimer#4]
**To Reproduce**
1. Configure the web part and save
2. Go to a different page
3. Go back to the page with the web part
4. The web part is back to saying "Configure"
5. When you go to edit only the Title is saved

**Comment by CreativeAcer** [comment]
reworked the webpart a bit, managed to maintain the default set date. Trying to figure out a way to maintain a recurring date, problem here is that it's self updating and propertybag is read only

**Comment by CreativeAcer** [comment]
Configuration is saved now, repeat function works. Delay function needs and update, currently repeat function is activated automatically.
