### ISSUE TITLE
Delay function isn't taken into account on reset

### ISSUE THREAD

**Issue by CreativeAcer** [CreativeAcer/SPFxCountdownTimer#5]
When the counter resets with the given amount of days, it happens instantly.
the delay amount isn't taken into account

**Comment by XopherDesign** [comment]
Do you have an ETA on this? Not trying to pressure you, I just need to know if I should wait to integrate into a project that I'm working on now or if I should wait.

**Comment by CreativeAcer** [comment]
I just finished the base for a different project so this issue should be next on the list.

However for now if you set the delay to 0 the restart functionality should work. It will just restart immediatly.

**Comment by CreativeAcer** [comment]
delay function updated, interval settings reworked
